import manage
import search_sites #django.core.exceptions.ImproperlyConfigured: You must define the HAYSTACK_SITECONF setting before using the search framework.
import settings
import test_settings
import urls	#Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.

import apps
import apps.equipment
import apps.equipment.admin
import apps.equipment.forms
import apps.equipment.models
import apps.equipment.tests
import apps.equipment.urls
import apps.equipment.views
import apps.equipment.migrations
#import apps.equipment.migrations.0001_initial
import apps.hpctardis
import apps.hpctardis.models
import apps.hpctardis.tests
import apps.hpctardis.urls
import apps.hpctardis.views
import apps.microtardis
import apps.microtardis.models
import apps.microtardis.tests
import apps.microtardis.views
import apps.microtardis.filters
import apps.microtardis.filters.microtags 

import tardis_portal
import tardis_portal.MultiPartForm
import tardis_portal.ParameterSetManager
import tardis_portal.ProcessExperiment
import tardis_portal.admin
import tardis_portal.constants
import tardis_portal.context_processors
import tardis_portal.download
import tardis_portal.errors
import tardis_portal.fields
import tardis_portal.forms
import tardis_portal.logging_middleware
import tardis_portal.managers
import tardis_portal.metsexporter
import tardis_portal.metshandler
import tardis_portal.metsparser
import tardis_portal.metsstruct


#import tardis_portal.models
import tardis_portal.rfc3339
#import tardis_portal.search_indexes
import tardis_portal.shortcuts
import tardis_portal.staging
#import tardis_portal.views
import tardis_portal.widgets
import tardis_portal.auth	
import tardis_portal.auth.authentication
import tardis_portal.auth.authservice
import tardis_portal.auth.decorators
import tardis_portal.auth.interfaces
import tardis_portal.auth.ip_auth
import tardis_portal.auth.ldap_auth
import tardis_portal.auth.localdb_auth
import tardis_portal.auth.utils
import tardis_portal.filters
#import tardis_portal.filters.exif
import tardis_portal.management
import tardis_portal.management.commands
#import tardis_portal.management.commands.echo
import tardis_portal.management.commands.backupdb
import tardis_portal.management.commands.createsuperuser
import tardis_portal.management.commands.dumpschemas
import tardis_portal.management.commands.loadschemas
import tardis_portal.migrations
#import tardis_portal.migrations.0001_initial
#import tardis_portal.migrations.0002_auto__add_field_parametername_order
import tardis_portal.minidetector
import tardis_portal.minidetector.useragents
import tardis_portal.publish
import tardis_portal.publish.interfaces
import tardis_portal.publish.publishservice
import tardis_portal.publish.rif_cs_profile
import tardis_portal.publish.rif_cs_profile.rif_cs_PublishProvider 		#path 
import tardis_portal.schema
import tardis_portal.schema.mets
import tardis_portal.schema.metssubs	#tardis.tardis_portal.schema.mets -> mets
import tardis_portal.templatetags
import tardis_portal.templatetags.basiccomparisonfilters
import tardis_portal.templatetags.dynurl
import tardis_portal.templatetags.experimentstats
import tardis_portal.templatetags.feed
import tardis_portal.templatetags.formfieldfilters
import tardis_portal.templatetags.uploadify_tags
import tardis_portal.templatetags.xmldate
import tardis_portal.tests
import tardis_portal.tests.ldap_ldif
import tardis_portal.tests.mock_vbl_auth				
import tardis_portal.tests.mock_vbl_download		
#import tardis_portal.tests.slapd
#import tardis_portal.tests.test_authentication
#import tardis_portal.tests.test_authorisation
#import tardis_portal.tests.test_authservice
#import tardis_portal.tests.test_download
#import tardis_portal.tests.test_filters
#import tardis_portal.tests.test_forms
#import tardis_portal.tests.test_ldap
#import tardis_portal.tests.test_models
#import tardis_portal.tests.test_parametersetmanager
#import tardis_portal.tests.test_staging
#import tardis_portal.tests.test_views
#import tardis_portal.tests.tests
#import tardis_portal.tests.urls

